# **Prólogo** {-}

La Universidad Nacional de Colombia fue fundada en 1867. Inició su actividad con las facultades de Artes y Oficios, Ciencias Naturales, Derecho, Ingeniería y Medicina, con 335 estudiantes y 45 profesores. En 1965 publicaba su primer _Boletín Estadístico de la Universidad_, y en 1966 _La Universidad en cifras_ como parte del informe de la rectoría del doctor José Félix Patiño Restrepo. Actualmente, la Universidad cuenta con 21 facultades, 9 sedes, 3095 profesores de planta y 54.028 estudiantes. Entre sus publicaciones está la revista _Estadísticas e Indicadores de la Universidad Nacional de Colombia_, que difunde su información en la página web de la universidad y cubre múltiples aspectos del quehacer institucional, lo que permite la interacción con el usuario y, lo que es más importante, está al alcance de cualquier ciudadano en línea. 

Este desarrollo informativo, con sus características propias, es bastante similar en la generalidad de las universidades colombianas: del papel a internet, de pocos datos a muchos datos, de distribución restringida solamente para la alta administración a todo el que tenga acceso al mundo web. Este transcurrir refleja la esencia de la historia de la cultura del dato al interior de las universidades públicas colombianas: la democratización de la información que pasó de ser un dato elitista exclusivo y nada participativo, a un dato que convive con los miembros de la comunidad universitaria. 

Si bien es cierto que el dato ahora es más democrático y de más fácil acceso, también es cierto que se presenta en mayores cantidades y con mayor rapidez: son muchos más los programas académicos, tanto de pregrado como de posgrado; son muchos más los estudiantes, los profesores; se realizan muchas más investigaciones y se publican muchas más revistas y artículos científicos, y un largo etcétera. Como clara consecuencia de este aumento de población y de actividades académicas se tienen más procesos que hacen que la administración universitaria de hoy se caracterice por un alto nivel de complejidad. 

Esta complejidad de la universidad obliga a implementar procesos de planeación que, a partir de la realidad pasada y presente, y con clara visión nacional e internacional, orienten el destino de la universidad hacia el cumplimiento riguroso y exitoso de sus misiones básicas para beneficio de una sociedad con enormes problemas sociales y deficiente desarrollo económico, necesitada de soluciones innovadoras dirigidas al mejoramiento continuo de la calidad de vida de las personas. Esta planeación solo puede realizarse adecuadamente con evidencias, esto es, con datos; son ellos los que dan cuenta objetiva de lo que han sido y son los aspectos que caracterizan la complejidad universitaria a la que nos referimos previamente. Más aún, la cantidad de datos que reflejan la dinámica cambiante de la realidad –y que hoy inundan a las instituciones universitarias–, expresados en cifras, imágenes, audios, videos provenientes de multitud de fuentes, en particular de páginas web, obliga a implementar y desarrollar procedimientos capaces de almacenarlas y desentrañar la información que contienen para, en consecuencia, asimilar rápidamente los cambios que se presentan y poder actuar sobre ellos a fin de orientar adecuadamente el devenir institucional. 

Si bien es cierto que las universidades desde siempre, públicas o privadas, han generado datos y han sabido registrarlos y utilizarlos como base para sus procesos de planeación, existen claras diferencias del ayer lejano de los siglos XIX y XX con los primeros años de este siglo XXI, respecto a las cifras o estadísticas universitarias, a su responsabilidad ante ellas, a su manejo, utilización y difusión. Estas diferencias son, a mi juicio, básicamente de dos tipos.

En primer lugar, está el papel del Estado. Antes el Estado controlaba la universidad asumiéndola como un ente oficial más que debía responder a la concepción política de los gobernantes de turno y, por tanto, tenía que caminar en paralelo con las ideologías reinantes. Con el argumento de formar “buenos ciudadanos”, las élites del poder en la larga historia republicana, salvo periodos cortos de liberalismo, dictaron normas que restringían severamente la autonomía y la libertad de cátedra. Bajo este esquema de dependencia ideológica del Estado era natural el nombramiento directo de las directivas universitarias, lo cual se terminó con la Constitución de 1991 que en su artículo 69 garantiza la autonomía universitaria: “Las universidades podrán darse sus directivas y regirse por sus propios estatutos, de acuerdo con la ley”. Sin embargo, se trata de una autonomía “controlada” ya que las universidades siguen dependiendo del Estado financiera y académicamente. En lo financiero, con aportes deficitarios a valor constante, y en lo académico, exceptuando la Universidad Nacional, controlando y autorizando la creación de nuevos programas académicos. A su vez, como idea novedosa y en respuesta al contexto internacional, la Ley 30 estimula a las universidades a someterse a procesos de acreditación y control de la calidad de sus servicios. Estos nuevos procesos conllevan la creación de indicadores que obligan a las universidades a asumir nuevas e inevitables formas de control de su gestión. 

Esta política de contar con indicadores de eficiencia de las universidades se corresponde con una serie de medidas conducentes a que todas las entidades oficiales rindan cuentas al Estado de su quehacer institucional. Es así que desde el Departamento Administrativo Nacional de Estadística (DANE), el Departamento Nacional de Planeación (DNP), el Departamento Administrativo de la Función Pública (DAFP), la Contraloría General de la República y el Ministerio de Tecnologías de la Información y las Comunicaciones (MinTIC), el Estado ha diseñado procedimientos y dictado normas que obligan a las instituciones públicas a informar sobre sus procesos y a manejarlos con base en reglas y en formatos específicos.

En el caso particular de las universidades, el Gobierno nacional las obliga a divulgar anualmente sus estadísticas básicas relacionadas con su labor académica, no solo como ejercicio de transparencia respecto a su gestión, sino también para informar a la ciudadanía, en particular a los estudiantes, las particularidades propias de cada universidad. Para satisfacer este objetivo, la Ley 30 creó el Sistema Nacional de Información de la Educación Superior (SNIES), el cual contiene la información de las instituciones de educación superior alusiva a diversos tipos de indicadores relacionados con la actividad académica y financiera de las universidades. A su vez, para fines de acreditación, se creó el Consejo Nacional de Acreditación (CNA). Uno de los aspectos de mayor peso en los procesos de acreditación son las autoevaluaciones que realizan los profesores, estudiantes y egresados con base en una batería de indicadores que, en el caso colombiano, es excesivamente meticulosa. 

En resumen, el Estado garantizó constitucionalmente la autonomía universitaria, pero obligó a las universidades a realizar procesos de transparencia, de buena gestión, control de calidad y de acreditación, y las introdujo en el mundo de los indicadores. Este nuevo proceder analítico no está exento de dificultades, empezando por la obvia confrontación entre lo tradicional y lo novedoso: gestión de planeación moderna basada en evidencias, es decir, en el manejo de enorme cantidad de datos e indicadores, y la planeación clásica de manejo de cifras y sus interpretaciones meramente descriptivas. Confrontación esta que todavía está lejos de ser superada. La resistencia al cambio. 

En segundo lugar, la cantidad y la variedad de información, junto con la velocidad con que se genera, sobrepasan la imaginación de cualquier funcionario administrativo universitario de los siglos pasados. Si hasta hace 20 años era posible manejar la información a través de un computador de baja capacidad y con metodología Excel, hoy en día sería absolutamente imposible sino se contara con los avances tecnológicos alcanzados en los años recientes, que permiten nuevas formas de captura de datos, almacenamiento, acceso y procesamiento. Simultáneamente con el avance tecnológico también se han generado multitud de técnicas y algoritmos conducentes a obtener la información no evidente subyacente a los datos, así como técnicas de análisis estadístico dirigidas a un mayor y mejor conocimiento de las relaciones o asociaciones que puedan existir entre variables y, por ende, dar mejor cuenta de procesos causa-efecto. 

Dadas así las cosas, se hace imperativo responder las siguientes preguntas que, sin duda, explican y orientan la gestión de la información cuantitativa en las universidades públicas colombianas: 

1.	¿Qué normas a nivel nacional e internacional orientan la construcción y disposición de estadísticas universitarias? 
2.	¿Qué técnicas existen para la captura, el almacenamiento, el acceso y el procesamiento de datos? 
3.	¿Cuál es la utilidad de las cifras cuantitativas en el contexto de la universidad pública contemporánea? Y ¿qué modelo organizacional se asocia con la gestión de datos? 
4.	¿Qué es y cómo se mide? Y ¿cómo se presentan los resultados de la medición? 

El asunto es ahora saber dónde pueden las universidades conocer con cierta extensión todos los aspectos mencionados sin tener que recurrir a muchas fuentes diversas y tomarse un tiempo largo de recopilación y análisis necesarios para organizar las respuestas y hacerlas claras, comprensibles y de utilidad. 

La respuesta está en este libro: _Gestión de la información cuantitativa en las universidades_ elaborado por la Oficina de Estadística de la Dirección Nacional de Planeación y Estadística de la Universidad Nacional. En los cuatro capítulos que constituyen el libro se encuentran, con lujo de detalles y referencias o enlaces adecuados, las respuestas a todas las preguntas previamente planteadas, desarrolladas en forma casi continua, sin omitir los detalles fundamentales y con un nivel de profundidad que no excluye la sencillez de su presentación en un estilo agradable y cercano al lector interesado en estos temas. 

El libro llena un vacío que existía en el escenario de la educación superior en Colombia. Aporta elementos conceptuales relacionados con la planeación inteligente o estratégica de las universidades, haciendo hincapié en desarrollar la cultura de toma decisiones fundamentadas en evidencias que solo pueden suministrar los datos. 

Agradezco el honor que me concedieron, que me permitió ser de los primeros lectores de esta obra, la cual no dudo en recomendar. 


```{block2, type='flushright', html.tag='p'}
**Gabriel Yáñez Canal**  
Jefe Unidad de Información y Análisis Estadístico (UIAES)  
Universidad Industrial de Santander
```


 




