# **Agradecimientos** {-}

El desarrollo de este libro implicó el aporte directo e indirecto de directivos, funcionarios administrativos, contratistas y estudiantes de la Universidad Nacional de Colombia, hecho que lo convierte en un producto derivado del trabajo en equipo y en comunidad. 

Nuestro agradecimiento al doctor Ignacio Mantilla Prada, exrector de la Universidad, por haber considerado la necesidad y la importancia de fortalecer la actividad estadística a nivel institucional e incluir en el Plan Global de Desarrollo 2016-2018, Autonomía Responsable y Excelencia Como Hábito, el proyecto “Fortalecimiento de la actividad estadística institucional – Fase I”, que nos permitió contar con los recursos financieros para el desarrollo de este libro y de otros productos institucionales cuyos resultados aspiran impactar el ejercicio administrativo en los años venideros. 

Al profesor Carlos Alberto Garzón Gaitán, director de la Dirección Nacional de Planeación y Estadística, gratitud por los años dedicados a estudiar y fomentar la importancia de la construcción, disposición y uso de estadísticas e indicadores en el escenario de la educación superior pública; sus aportes son ejemplo y fuente de inspiración para la planeación, la gestión y la actividad estadística en el ámbito universitario. Así mismo, nuestro agradecimiento por su defensa y apoyo en las etapas de concepción, desarrollo y finalización de este documento, obra y producto de su gestión. Un agradecimiento especial al profesor Herbert Giraldo Gómez, profesor de la Universidad Nacional de Colombia y exdirector de la Dirección Nacional de Planeación y Estadística de la Universidad por dar continuidad, fortalecer el equipo de trabajo y apoyar el desarrollo de este proyecto en los momentos de dificultad. 

A Juliana López Carrascal por la rigurosidad en la exploración de los antecedentes históricos del uso de la estadística en el escenario administrativo público, por el redescubrimiento de conceptos propios del lenguaje de la cuantificación y medición en el contexto estatal, y por los aportes profundos, precisos y oportunos en favor de la gestión estadística en las universidades públicas. A María Claudia Galindo Gonzales, profesional de la Oficina Nacional de Estadística, por la conservación de la información estadística histórica de la Universidad y por la rigurosidad en la gestión de los datos institucionales; sin su trabajo, este proyecto no hubiese podido ser una realidad. A Yenny Aleth Aldana Barrera, jefe de la Oficina Nacional de Estadística, por su liderazgo y por el apoyo administrativo decidido en pro del fortalecimiento de la actividad estadística en la Universidad Nacional de Colombia. A Liliana Andrea Gaitán Mendoza y Diana Yamile Salamanca, nuestro agradecimiento por el apoyo recibido en la provisión de material para algunos apartados de este documento y por la gestión de microdatos históricos institucionales, respectivamente. 

A los estudiantes de estadística Martín Andrés Macías Quintero, Daniel Rodríguez Chávez y Hernán David Torres Cardona, por su compromiso, calidad en el trabajo, curiosidad y dedicación ante los retos propuestos. El trabajo de Martín nos permite disponer de la versión web de este libro y la interacción requerida entre la estadística y la ingeniería de sistemas a través del trabajo en la nube. El aporte de Daniel nos permite contar con una gran diversidad de objetos gráficos web a través de los cuales hoy se visualiza la información estratégica oficial de la Universidad, y el trabajo de Hernán nos permite acceder a la información cuantitativa institucional desde una perspectiva geográfica, así como disponer de un piloto para la presentación de la información estadística en las sedes ubicadas en las fronteras de nuestro país. Al estudiante de ingeniería de sistemas, Emilbert Alexis Ortiz Bohorquez, agradecimiento por el desarrollo del sitio web de estadísticas de la Universidad y por enfrentar y superar, con el profesionalismo y la curiosidad requerida, los diversos retos que este implicó. 

A Constanza Elena Rojas Olivera, profesional especializada de la Dirección Nacional de Planeación y Estadística, gratitud por el acompañamiento institucional en el monitoreo y seguimiento al desarrollo del proyecto que permitió obtener este libro y otros productos institucionales; sus aportes continúan siendo pieza clave en el devenir de nuestras actividades. A todos y cada uno de los miembros del equipo de trabajo de la Dirección Nacional de Planeación y Estadística de la Universidad Nacional de Colombia, nuestro agradecimiento por hacer los días de trabajo siempre placenteros. 

Al profesor Gabriel Yáñez Canal, director de la Unidad de Información y Análisis Estadístico de la Universidad Industrial de Santander, inmensa gratitud por su disposición, apoyo y tiempo dedicado a la revisión de este libro, y por sus comentarios, oportunos y precisos, los cuales aportaron de manera significativa al mejoramiento del contenido de este texto. Finalmente, un agradecimiento y reconocimiento especial a todos los funcionarios de la Universidad Nacional de Colombia que a diario registran y gestionan la información que sirve de base para la construcción y disposición de las cifras institucionales sin las cuales este trabajo carecería de utilidad y sentido. 

