# **Introducción** {-}

```{block2, type='flushright', html.tag='p'}
_La neblina de la información puede debilitar el conocimiento_\
**D.J. Boorstin**
```

## **La era de la sobreinformación** {-}

Hace poco menos de 50 años era difícil acceder a cierta información estadística o saber la opinión de cientos, miles o millones de personas; ahora se recibe información a manos llenas, incluso sin necesidad de buscarla. Esto ha conllevado cambios sociales, económicos, culturales y psicológicos. Tenemos la sensación, o la fantasía, de contar con mucha más información que antes, pero esto viene acompañado de algunas complicaciones: qué hacer con tanta información, cómo elegir la más relevante, cómo estar al día, cómo estar seguro de su confiabilidad y, quizás uno de los aspectos más importantes, cómo tomar decisiones basadas en ella. 

Se han utilizado diferentes términos que permiten acercarse a la situación contemporánea en relación con la información, tales como sobreinformación, infoxicación, infopolución, _information overload_, infonomía o _big bang_ de la información. En general, estos se refieren al incremento vertiginoso de información, “la Humanidad, en su totalidad, nunca había dispuesto de un acceso tan rápido a un volumen de datos que aumenta cada segundo” [@Caldevilla2013, p. 35]. 

Se reconocen algunos aspectos positivos de esta situación y de las posibilidades contemporáneas gracias a los avances en las nuevas tecnologías de la información y las comunicaciones (TIC); por ejemplo, se evidencia una relación más cercana del lector-autor, una mayor horizontalidad e interactividad entre emisores y receptores de mensajes, un crecimiento exponencial del conocimiento y un aumento de la democratización de este. Sin embargo, a su vez se advierten algunas consecuencias desfavorables, como la manipulación premeditada en redes sociales, el incremento del uso de la _posverdad_, que distorsiona deliberadamente la realidad para modelar la opinión pública, la mercantilización del conocimiento y la disminución de las capacidades individuales (p. ej., cerebro agobiado), grupales e institucionales para seleccionar, absorber y transformar la información que se recibe. 

Ante esta situación se sugieren diversas estrategias cuyos elementos comunes son: tener la capacidad y la posibilidad de filtrar la información recibida (filtros previos a la lectura, división del trabajo, metainformación, clasificación y priorización); conocer y aplicar técnicas de procesado masivo y relacional de la información (p. ej., _Big Data_, minería de datos, analítica de la información, uso de inteligencia artificial) y contar con mecanismos de borrado^[Ver _La sobreinformación en la era internet_, del Equipo Enliza (2014), en http://www.enliza.es/SECCIONES_2/2_SOBREINFORMACION/sobreinformacion.php]. 

Esta compleja situación se vive diariamente en las universidades, se recibe información sobre tendencias y recomendaciones mundiales; existe información de la institución, que se compila para contestar a demandas internas y externas de datos que permitan medir calidad o efectividad, o responder a organismos de control; se establecen requerimientos desde las diferentes unidades y procesos, y órganos directivos que necesitan tomar buenas decisiones y contar con la información que los apoye; se cuenta con estadísticas e información nacional sobre el sector educativo, así como sobre la situación del país, entre otros. Esto significa montañas de datos que pueden perder sentido o no servir como referente a la toma de decisiones acertadas si no se realiza una adecuada gestión de la información. 

## **Especificidad de la gestión universitaria** {-}

La universidad contemporánea cuenta con unos atributos que la diferencian de cualquier otra organización. De acuerdo con un estudio adelantado por la Comisión Nacional de Evaluación y Acreditación Universitaria (Coneau) (2000) de Argentina, entre sus características particulares se incluyen las siguientes:

+ Es una organización compleja, es decir, está compuesta por elementos muy diversos, interrelacionados entre sí, sin un orden fijo (es dinámica), ni una jerarquía lineal, con reglas formales y también un alto número de reglas informales o latentes. Esta complejidad es coherente con la naturaleza de su objeto principal: formación.

+ Sus misiones y objetivos son generales y ambiguos, en tanto su significado o interpretación varían según los diferentes grupos de interés que participan e influyen en la educación superior, y viven en una negociación permanente.

+ Maneja proyectos abiertos, ya que se ve influida en gran medida por su interacción con sectores extraorganizacionales.

+ Se vive en un sistema plural de poder, con diversos intereses, conflictos, relaciones de poder y un grado alto de incertidumbre y reactividad.

+ Otros como: carácter multidimensional, modalidad colegiada de toma de decisiones, tecnologías educativas y de investigación con resultados inciertos, ámbito de convivencia y tensiones entre grupos, diversidad de criterios para la legitimación de los liderazgos, lealtades múltiples de su comunidad a grupos disciplinarios, grupos políticos u otros, _sistemas de información fuertemente determinados por las culturas académicas que coexisten_, multiplicidad de articulaciones externas, conflictos de valores, entre otros.

> Debido a estos atributos, la gestión universitaria se desenvuelve siempre en presencia de tensiones, las que deben ser canalizadas positivamente, sin que ello alcance para suprimirlas. Puede plantearse la hipótesis de que las instituciones universitarias exitosas son aquellas que pueden canalizar positivamente esas tensiones. [@Coneau, pág. 42]

Esto lleva a que la gestión universitaria enfrente diferentes desafíos tales como: actuar con autonomía en consonancia con restricciones externas (p. ej., normativa nacional, relación con entidades gubernamentales, financiamiento, sector empresarial, movimientos sociales) y las discrecionalidades internas (regímenes administrativos, estatutos y normas internas, autoridades y liderazgos internos, etc.); brindar el marco para las funciones misionales (aunque sea difícil evaluar un impacto directo de sus decisiones); evitar el uso acrítico de instrumentos desarrollados para organizaciones muy diferentes, como aquellas con ánimo de lucro, altamente jerarquizadas, con poca autonomía de sus integrantes, que busquen resultados medibles a corto plazo y con indicadores de resultados fácilmente cuantificables.

Existen diversas recomendaciones para las personas encargadas de la gestión universitaria, como: identificar el marco organizativo, así como el tipo de gobierno y el nivel de gobernabilidad que caracteriza a la institución a su cargo; desarrollar habilidades de planeación y negociación, así como de escucha y manejo de conflictos, tanto para el ámbito estratégico como para el operativo; mantener la coherencia entre la misión y los diversos proyectos institucionales; contribuir a la integración institucional en diferentes aspectos (integración de objetivos, intertemporal, de procesos, de actividades, integración con el medio, con la eficiencia en la gestión de recursos, integración de aportes y de continuidad y cambio); capacidad de tomar acciones en los momentos precisos considerando las posibles consecuencias; preparar relevamientos de liderazgo o generacionales. Adicionalmente, entre las más importantes y que se relacionan directamente con este libro: tomar decisiones basadas en información clara y confiable. Para ello es fundamental una adecuada gestión de la información y, en esta, de la información cuantitativa.

## **Gestión de la información cuantitativa en las universidades** {-}

Este libro aborda elementos centrales para la gestión de la información cuantitativa en las universidades en la era de la sobreinformación. Aunque centra su atención en el escenario de la universidad pública, su contenido puede ser útil para las demás entidades que hacen parte del Estado colombiano y que se encuentran interesadas o inmersas en planes o proyectos orientados a extraer y hacer uso de la información cuantitativa contenida en los datos institucionales. 

El Capítulo 1, titulado _Nueva gestión pública e información cuantitativa en las universidades_, aborda los aspectos regulatorios, las necesidades y las demandas de información cuantitativa que viven en la actualidad las universidades en Colombia, derivados de las nuevas formas de regular y orientar el ejercicio administrativo público, con diversos instrumentos que se han creado y popularizado principalmente durante las últimas dos décadas. 

En este primer capítulo se describen los principales frentes que abordan las universidades, en especial las públicas, todos ellos acompañados de demandas de información cuantitativa, y que están cambiando la concepción y la forma como estas deben ser gestionadas y administradas, tales como: el protagonismo de la planeación; la adopción, adaptación e implementación de sistemas integrados de calidad para la prestación de servicios institucionales bajo un enfoque orientado por procesos; el control interno y el control posterior por parte de las contralorías; la apuesta del Estado por el uso masivo de las nuevas tecnologías de la información y las comunicaciones a través de la implementación de la estrategia de Gobierno Digital; la necesidad de aumentar los niveles de transparencia institucional y la obligación de rendir cuentas de manera periódica y pública a la sociedad; el incremento de la normatividad encaminada a la protección y el buen uso de los datos personales; la creación de la política nacional de explotación de datos –_Big Data_–, y la conformación del Sistema Estadístico Nacional (SEN). 

Así mismo, se presenta brevemente el Sistema de Aseguramiento de la Calidad en la Educación Superior, que implica tanto la autoevaluación como la evaluación externa, con miras al registro calificado y a la acreditación nacional e internacional en alta calidad de instituciones de educación superior (IES) y programas académicos; el Sistema Universita- rio Estatal (SUE); la disposición de microdatos para diferentes sistemas nacionales de información y el surgimiento de cientos de _rankings_ universitarios de alcance mundial, nacional y sectorial. Finalmente, se incluye en este capítulo una descripción breve de cómo la Universidad Nacional de Colombia viene trabajando los diversos frentes que ha traído la nueva gestión pública. 

El Capítulo 2, titulado _El boom de los datos y el protagonismo de la tecnología_, ilustra el auge y la importancia que están experimentando en la actualidad los datos y el papel protagónico de la tecnología en su gestión. La diversidad en los tipos de datos, el surgimiento del fenómeno del _Big Data_, el incremento en la disposición y uso de técnicas de minería o analítica de datos, el surgimiento de arquitecturas tecnológicas centradas en la gestión de los datos como la provista por la inteligencia de negocios, así como el incremento en el número de competencias profesionales requeridas para un adecuado estudio y uso de los datos e incluidas en la llamada ciencia de los datos, se han sumado a la estadística, disciplina tradicional de estudio y disposición de las cifras oficiales, para conformar una amplia gama de herramientas, disciplinas y actores interesados en el estudio y la forma como debe ser gestionada la información cuantitativa en el ámbito de las universidades. 

El Capítulo 3, titulado _Gestión de la información cuantitativa en las universidades: el encuentro de dos mundos_, expone los principales elementos que intervienen en la gestión contemporánea de los datos agrupados en dos mundos: el contexto normativo e institucional de la información cuantitativa pública y el escenario académico y técnico de los datos. En primer lugar, la claridad en el propósito buscado a través de la gestión de los datos institucionales; el conocimiento de la normatividad expedi- da por diferentes actores del contexto internacional, nacional y sectorial en materia de regulación y orientación del ejercicio estadístico; las demandas de información que experimentan las universidades, sumado a los modelos organizacionales y el lenguaje dominante en términos cuantitativos en estas, conforman el _mundo normativo e institucional_ que debe ser estudiado y considerado en el escenario de la gestión de la información cuantitativa disponible a nivel institucional. 

En segundo lugar, la gestión de la información cuantitativa exige conocimiento y dominio de las diversas aproximaciones existentes para el estudio de los datos, así como la disposición y experticia en el uso de las herramientas, principalmente tecnológicas, requeridas para el ejercicio estadístico moderno. Tipologías de los datos existentes y disponibles a nivel de las universidades, disciplinas o tendencias bajo las cuales pueden ser estudiados; métodos y técnicas disponibles para su análisis; bases conceptuales que soportan los métodos y las técnicas así como selección, entre cientos disponibles, de las herramientas tecnológicas existentes y requeridas para la gestión y disposición de la información cuantitativa a nivel de las universidades, conforman el _mundo académico y técnico_ que acompaña una apuesta orientada a la gestión de la información cuantitativa en las universidades. 

El Capítulo 4, titulado _Cuantificación y medición en las universidades. Una aproximación descriptiva_, apuesta por reivindicar la importancia del estudio descriptivo de los datos institucionales disponibles en las universidades, en medio del furor que despierta en la actualidad el uso de técnicas complejas y de vanguardia como las derivadas del _Big Data_, la analítica de datos, la ciencia de los datos y el uso masivo de la tecnología. Para ello, se propone diferenciar el concepto de _estadísticas institucionales_ de la noción de _indicadores_ como instrumentos complementarios que permiten explorar el comportamiento pasado y el presente numérico de las universidades –las estadísticas– así como monitorear el avance en el cumplimiento de los planes de desarrollo institucionales –los indicadores de desarrollo o cumplimiento–. 

En este capítulo se analizan las principales características de las _estadísticas_, tales como: ser cifras de naturaleza descriptiva derivadas de poblaciones o muestras; tener un carácter agregado; ser susceptibles de ser desagregadas/presentadas de manera temporal, geográfica o temática; representar el presente y el pasado numérico de las universidades; incluir a poblaciones minoritarias o en condición de desigualdad; presentar la información de manera tabular y gráfica; hacer uso de conceptos, estándares y codificaciones que faciliten su comparación; estar disponibles a través de múltiples medios de difusión y comunicación; hacer uso de las TIC; estar respaldadas por un proceso estadístico que garantice su continuidad, y servir de base para la construcción de nuevas estadísticas, indicadores o sistemas de medición al interior de las universidades. Los _indicadores de desarrollo_, útiles para el monitoreo del cumplimiento de políticas institucionales, se abordan en este documento de manera parcial y general, apoyándonos para ello en los trabajos adelantados en la materia por el Departamento Nacional de Planeación (DNP). 

Finalmente, invitamos a los lectores para que accedan a la versión [web de este libro](https://estadisticaun.github.io/L_Conceptual/), y a que exploren, al tiempo que avanzan en su lectura, el sitio web de estadísticas institucionales http://estadisticas.unal.edu.co/ donde, además de aplicarse el conocimiento contenido en este trabajo, se dispone del legado histórico estadístico institucional, la documentación empleada en la gestión estadística interna, así como las principales cifras estratégicas de la Universidad Nacional de Colombia a través de las cuales se aspira aumentar los niveles de transparencia institucional y, sobre todo, rendir cuentas a la sociedad de manera numérica, abierta y permanente sobre los principales resultados e impactos sociales derivados de contar en el país con esta universidad pública y nacional. 

